package clickandbuy.upc.edu.core.entity;
// Generated Sep 27, 2013 3:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer catCodigo;
     private String catNombre;
     private Set productos = new HashSet(0);

    public Categoria() {
    }

	
    public Categoria(String catNombre) {
        this.catNombre = catNombre;
    }
    public Categoria(String catNombre, Set productos) {
       this.catNombre = catNombre;
       this.productos = productos;
    }
   
    public Integer getCatCodigo() {
        return this.catCodigo;
    }
    
    public void setCatCodigo(Integer catCodigo) {
        this.catCodigo = catCodigo;
    }
    public String getCatNombre() {
        return this.catNombre;
    }
    
    public void setCatNombre(String catNombre) {
        this.catNombre = catNombre;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


