package clickandbuy.upc.edu.core.entity;
// Generated Oct 16, 2013 8:23:13 PM by Hibernate Tools 3.2.1.GA

import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

    private Integer cliCodigo;
    private String cliNombreusuario;
    private String cliContrasenia;
    private String cliNombreempresa;
    private String cliDireccion;
    private String cliRuc;
    private Set pedidos = new HashSet(0);
    private Set logs = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String cliNombreusuario, String cliNombreempresa, String cliDireccion, String cliRuc) {
        this.cliNombreusuario = cliNombreusuario;
        this.cliNombreempresa = cliNombreempresa;
        this.cliDireccion = cliDireccion;
        this.cliRuc = cliRuc;
    }

    public Cliente(String cliNombreusuario, String cliContrasenia, String cliNombreempresa, String cliDireccion, String cliRuc, Set pedidos, Set logs) {
        this.cliNombreusuario = cliNombreusuario;
        this.cliContrasenia = cliContrasenia;
        this.cliNombreempresa = cliNombreempresa;
        this.cliDireccion = cliDireccion;
        this.cliRuc = cliRuc;
        this.pedidos = pedidos;
        this.logs = logs;
    }

    public Integer getCliCodigo() {
        return this.cliCodigo;
    }

    public void setCliCodigo(Integer cliCodigo) {
        this.cliCodigo = cliCodigo;
    }

    public String getCliNombreusuario() {
        return this.cliNombreusuario;
    }

    public void setCliNombreusuario(String cliNombreusuario) {
        this.cliNombreusuario = cliNombreusuario;
    }

    public String getCliContrasenia() {
        return this.cliContrasenia;
    }

    public void setCliContrasenia(String cliContrasenia) {
        this.cliContrasenia = cliContrasenia;
    }

    public String getCliNombreempresa() {
        return this.cliNombreempresa;
    }

    public void setCliNombreempresa(String cliNombreempresa) {
        this.cliNombreempresa = cliNombreempresa;
    }

    public String getCliDireccion() {
        return this.cliDireccion;
    }

    public void setCliDireccion(String cliDireccion) {
        this.cliDireccion = cliDireccion;
    }

    public String getCliRuc() {
        return this.cliRuc;
    }

    public void setCliRuc(String cliRuc) {
        this.cliRuc = cliRuc;
    }

    public Set getPedidos() {
        return this.pedidos;
    }

    public void setPedidos(Set pedidos) {
        this.pedidos = pedidos;
    }

    public Set getLogs() {
        return this.logs;
    }

    public void setLogs(Set logs) {
        this.logs = logs;
    }
}
