package clickandbuy.upc.edu.core.entity;
// Generated Sep 27, 2013 3:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int cliCodigo;
     private String cliNombreusuario;
     private String cliContrasenia;
     private String cliNombreempresa;
     private String cliDireccion;
     private Long cliRuc;
     private Set logs = new HashSet(0);
     private Set historialcarritos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int cliCodigo) {
        this.cliCodigo = cliCodigo;
    }
    public Cliente(int cliCodigo, String cliNombreusuario, String cliContrasenia, String cliNombreempresa, String cliDireccion, Long cliRuc, Set logs, Set historialcarritos) {
       this.cliCodigo = cliCodigo;
       this.cliNombreusuario = cliNombreusuario;
       this.cliContrasenia = cliContrasenia;
       this.cliNombreempresa = cliNombreempresa;
       this.cliDireccion = cliDireccion;
       this.cliRuc = cliRuc;
       this.logs = logs;
       this.historialcarritos = historialcarritos;
    }
   
    public int getCliCodigo() {
        return this.cliCodigo;
    }
    
    public void setCliCodigo(int cliCodigo) {
        this.cliCodigo = cliCodigo;
    }
    public String getCliNombreusuario() {
        return this.cliNombreusuario;
    }
    
    public void setCliNombreusuario(String cliNombreusuario) {
        this.cliNombreusuario = cliNombreusuario;
    }
    public String getCliContrasenia() {
        return this.cliContrasenia;
    }
    
    public void setCliContrasenia(String cliContrasenia) {
        this.cliContrasenia = cliContrasenia;
    }
    public String getCliNombreempresa() {
        return this.cliNombreempresa;
    }
    
    public void setCliNombreempresa(String cliNombreempresa) {
        this.cliNombreempresa = cliNombreempresa;
    }
    public String getCliDireccion() {
        return this.cliDireccion;
    }
    
    public void setCliDireccion(String cliDireccion) {
        this.cliDireccion = cliDireccion;
    }
    public Long getCliRuc() {
        return this.cliRuc;
    }
    
    public void setCliRuc(Long cliRuc) {
        this.cliRuc = cliRuc;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }
    public Set getHistorialcarritos() {
        return this.historialcarritos;
    }
    
    public void setHistorialcarritos(Set historialcarritos) {
        this.historialcarritos = historialcarritos;
    }




}


