package clickandbuy.upc.edu.core.entity;
// Generated Sep 27, 2013 3:28:11 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Historialcarrito generated by hbm2java
 */
public class Historialcarrito implements java.io.Serializable {

    private int hisCodigo;
    private Cliente cliente;
    private Carrito carrito;
    private Date hisFechahora;
    private double hisPreciototal;
    private String hisEstado;

    public Historialcarrito() {
    }

    public Historialcarrito(int hisCodigo, Cliente cliente, Carrito carrito, double hisPreciototal, String hisEstado) {
        this.hisCodigo = hisCodigo;
        this.cliente = cliente;
        this.carrito = carrito;
        this.hisPreciototal = hisPreciototal;
        this.hisEstado = hisEstado;
    }

    public Historialcarrito(int hisCodigo, Cliente cliente, Carrito carrito, Date hisFechahora, double hisPreciototal, String hisEstado) {
        this.hisCodigo = hisCodigo;
        this.cliente = cliente;
        this.carrito = carrito;
        this.hisFechahora = hisFechahora;
        this.hisPreciototal = hisPreciototal;
        this.hisEstado = hisEstado;
    }

    public int getHisCodigo() {
        return this.hisCodigo;
    }

    public void setHisCodigo(int hisCodigo) {
        this.hisCodigo = hisCodigo;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Carrito getCarrito() {
        return this.carrito;
    }

    public void setCarrito(Carrito carrito) {
        this.carrito = carrito;
    }

    public Date getHisFechahora() {
        return this.hisFechahora;
    }

    public void setHisFechahora(Date hisFechahora) {
        this.hisFechahora = hisFechahora;
    }

    public double getHisPreciototal() {
        return this.hisPreciototal;
    }

    public void setHisPreciototal(double hisPreciototal) {
        this.hisPreciototal = hisPreciototal;
    }

    public String getHisEstado() {
        return this.hisEstado;
    }

    public void setHisEstado(String hisEstado) {
        this.hisEstado = hisEstado;
    }
}
