package clickandbuy.upc.edu.core.entity;
// Generated Oct 16, 2013 8:23:13 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Log generated by hbm2java
 */
public class Log implements java.io.Serializable {

    private Integer logCodigo;
    private Cliente cliente;
    private Date logFechahora;
    private String logUrl;
    private String logIp;
    private String logExcepcion;

    public Log() {
    }

    public Log(Cliente cliente, Date logFechahora, String logUrl, String logIp, String logExcepcion) {
        this.cliente = cliente;
        this.logFechahora = logFechahora;
        this.logUrl = logUrl;
        this.logIp = logIp;
        this.logExcepcion = logExcepcion;
    }

    public Integer getLogCodigo() {
        return this.logCodigo;
    }

    public void setLogCodigo(Integer logCodigo) {
        this.logCodigo = logCodigo;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Date getLogFechahora() {
        return this.logFechahora;
    }

    public void setLogFechahora(Date logFechahora) {
        this.logFechahora = logFechahora;
    }

    public String getLogUrl() {
        return this.logUrl;
    }

    public void setLogUrl(String logUrl) {
        this.logUrl = logUrl;
    }

    public String getLogIp() {
        return this.logIp;
    }

    public void setLogIp(String logIp) {
        this.logIp = logIp;
    }

    public String getLogExcepcion() {
        return this.logExcepcion;
    }

    public void setLogExcepcion(String logExcepcion) {
        this.logExcepcion = logExcepcion;
    }
}
