package clickandbuy.upc.edu.core.entity;
// Generated Oct 16, 2013 8:23:13 PM by Hibernate Tools 3.2.1.GA

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 * Pedido generated by hbm2java
 */
public class Pedido implements java.io.Serializable {

    private Integer pedCodigo;
    private Cliente cliente;
    private Date pedFechahora;
    private String pedTipo;
    private List<Productoxpedido> productoxpedidos = new ArrayList<Productoxpedido>();

    public Pedido() {
    }

    public Pedido(Cliente cliente, String pedTipo) {
        this.cliente = cliente;
        this.pedTipo = pedTipo;
    }

    public Pedido(Cliente cliente, Date pedFechahora, String pedTipo, List<Productoxpedido> productoxpedidos) {
        this.cliente = cliente;
        this.pedFechahora = pedFechahora;
        this.pedTipo = pedTipo;
        this.productoxpedidos = productoxpedidos;
    }

    public Integer getPedCodigo() {
        return this.pedCodigo;
    }

    public void setPedCodigo(Integer pedCodigo) {
        this.pedCodigo = pedCodigo;
    }

    public Cliente getCliente() {
        return this.cliente;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }

    public Date getPedFechahora() {
        return this.pedFechahora;
    }

    public void setPedFechahora(Date pedFechahora) {
        this.pedFechahora = pedFechahora;
    }

    public String getPedTipo() {
        return this.pedTipo;
    }

    public void setPedTipo(String pedTipo) {
        this.pedTipo = pedTipo;
    }

    public List<Productoxpedido> getProductoxpedidos() {
        return this.productoxpedidos;
    }

    public void setProductoxpedidos(List<Productoxpedido> productoxpedidos) {
        this.productoxpedidos = productoxpedidos;
    }
}
