package clickandbuy.upc.edu.core.entity;
// Generated Oct 16, 2013 8:23:13 PM by Hibernate Tools 3.2.1.GA

/**
 * ProductoxpedidoId generated by hbm2java
 */
public class ProductoxpedidoId implements java.io.Serializable {

    private int propedCodigopedido;
    private int propedCodigoproducto;

    public ProductoxpedidoId() {
    }

    public ProductoxpedidoId(int propedCodigopedido, int propedCodigoproducto) {
        this.propedCodigopedido = propedCodigopedido;
        this.propedCodigoproducto = propedCodigoproducto;
    }

    public int getPropedCodigopedido() {
        return this.propedCodigopedido;
    }

    public void setPropedCodigopedido(int propedCodigopedido) {
        this.propedCodigopedido = propedCodigopedido;
    }

    public int getPropedCodigoproducto() {
        return this.propedCodigoproducto;
    }

    public void setPropedCodigoproducto(int propedCodigoproducto) {
        this.propedCodigoproducto = propedCodigoproducto;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }
        if ((other == null)) {
            return false;
        }
        if (!(other instanceof ProductoxpedidoId)) {
            return false;
        }
        ProductoxpedidoId castOther = (ProductoxpedidoId) other;

        return (this.getPropedCodigopedido() == castOther.getPropedCodigopedido())
                && (this.getPropedCodigoproducto() == castOther.getPropedCodigoproducto());
    }

    public int hashCode() {
        int result = 17;

        result = 37 * result + this.getPropedCodigopedido();
        result = 37 * result + this.getPropedCodigoproducto();
        return result;
    }
}
