package clickandbuy.upc.edu.core.entity;
// Generated Oct 16, 2013 8:23:13 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

    private Integer prodCodigo;
    private Categoria categoria;
    private String prodNombre;
    private int prodStock;
    private BigDecimal prodPreciocompra;
    private String prodDescripcion;
    private BigDecimal prodPrecioventa;
    private Set productoxpedidos = new HashSet(0);

    public Producto() {
    }

    public Producto(Categoria categoria, String prodNombre, int prodStock, BigDecimal prodPreciocompra, String prodDescripcion, BigDecimal prodPrecioventa) {
        this.categoria = categoria;
        this.prodNombre = prodNombre;
        this.prodStock = prodStock;
        this.prodPreciocompra = prodPreciocompra;
        this.prodDescripcion = prodDescripcion;
        this.prodPrecioventa = prodPrecioventa;
    }

    public Producto(Categoria categoria, String prodNombre, int prodStock, BigDecimal prodPreciocompra, String prodDescripcion, BigDecimal prodPrecioventa, Set productoxpedidos) {
        this.categoria = categoria;
        this.prodNombre = prodNombre;
        this.prodStock = prodStock;
        this.prodPreciocompra = prodPreciocompra;
        this.prodDescripcion = prodDescripcion;
        this.prodPrecioventa = prodPrecioventa;
        this.productoxpedidos = productoxpedidos;
    }

    public Integer getProdCodigo() {
        return this.prodCodigo;
    }

    public void setProdCodigo(Integer prodCodigo) {
        this.prodCodigo = prodCodigo;
    }

    public Categoria getCategoria() {
        return this.categoria;
    }

    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }

    public String getProdNombre() {
        return this.prodNombre;
    }

    public void setProdNombre(String prodNombre) {
        this.prodNombre = prodNombre;
    }

    public int getProdStock() {
        return this.prodStock;
    }

    public void setProdStock(int prodStock) {
        this.prodStock = prodStock;
    }

    public BigDecimal getProdPreciocompra() {
        return this.prodPreciocompra;
    }

    public void setProdPreciocompra(BigDecimal prodPreciocompra) {
        this.prodPreciocompra = prodPreciocompra;
    }

    public String getProdDescripcion() {
        return this.prodDescripcion;
    }

    public void setProdDescripcion(String prodDescripcion) {
        this.prodDescripcion = prodDescripcion;
    }

    public BigDecimal getProdPrecioventa() {
        return this.prodPrecioventa;
    }

    public void setProdPrecioventa(BigDecimal prodPrecioventa) {
        this.prodPrecioventa = prodPrecioventa;
    }

    public Set getProductoxpedidos() {
        return this.productoxpedidos;
    }

    public void setProductoxpedidos(Set productoxpedidos) {
        this.productoxpedidos = productoxpedidos;
    }
}
