package clickandbuy.upc.edu.core.entity;
// Generated Sep 27, 2013 3:28:11 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer prodCodigo;
     private Categoria categoria;
     private String prodNombre;
     private int prodStock;
     private double prodPreciocompra;
     private String prodDescripcion;
     private double prodPrecioventa;
     private Set carritos = new HashSet(0);

    public Producto() {
    }

	
    public Producto(Categoria categoria, String prodNombre, int prodStock, double prodPreciocompra, String prodDescripcion, double prodPrecioventa) {
        this.categoria = categoria;
        this.prodNombre = prodNombre;
        this.prodStock = prodStock;
        this.prodPreciocompra = prodPreciocompra;
        this.prodDescripcion = prodDescripcion;
        this.prodPrecioventa = prodPrecioventa;
    }
    public Producto(Categoria categoria, String prodNombre, int prodStock, double prodPreciocompra, String prodDescripcion, double prodPrecioventa, Set carritos) {
       this.categoria = categoria;
       this.prodNombre = prodNombre;
       this.prodStock = prodStock;
       this.prodPreciocompra = prodPreciocompra;
       this.prodDescripcion = prodDescripcion;
       this.prodPrecioventa = prodPrecioventa;
       this.carritos = carritos;
    }
   
    public Integer getProdCodigo() {
        return this.prodCodigo;
    }
    
    public void setProdCodigo(Integer prodCodigo) {
        this.prodCodigo = prodCodigo;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getProdNombre() {
        return this.prodNombre;
    }
    
    public void setProdNombre(String prodNombre) {
        this.prodNombre = prodNombre;
    }
    public int getProdStock() {
        return this.prodStock;
    }
    
    public void setProdStock(int prodStock) {
        this.prodStock = prodStock;
    }
    public double getProdPreciocompra() {
        return this.prodPreciocompra;
    }
    
    public void setProdPreciocompra(double prodPreciocompra) {
        this.prodPreciocompra = prodPreciocompra;
    }
    public String getProdDescripcion() {
        return this.prodDescripcion;
    }
    
    public void setProdDescripcion(String prodDescripcion) {
        this.prodDescripcion = prodDescripcion;
    }
    public double getProdPrecioventa() {
        return this.prodPrecioventa;
    }
    
    public void setProdPrecioventa(double prodPrecioventa) {
        this.prodPrecioventa = prodPrecioventa;
    }
    public Set getCarritos() {
        return this.carritos;
    }
    
    public void setCarritos(Set carritos) {
        this.carritos = carritos;
    }




}


